apiVersion: "v1"
kind: "Service"
metadata:
  name: "dentocare-backend-service"
  namespace: "default"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
  selector:
    component: "dentocare-backend"
  type: NodePort
  